### ISSUE TITLE
Vite unable to find vite.templatus-inertia.test

### ISSUE THREAD

**Issue by TaylorJonesTRT** [templatus/templatus-inertia#1522]
Hello!

I've just recently found this and am ecstatic as I don't have to get it all setup myself now.

I am running into the following error though after following the steps in the README. 

```
system  | Listening at ./.overmind.sock
vite    | Started with pid 3963...
browser | Started with pid 3964...
vite    | 10:21:48 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.
vite    |
vite    | @tabler/icons-svelte@2.44.0
vite    |
vite    | Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
vite    | Forced re-optimization of dependencies
vite    | error when starting dev server:
vite    | Error: getaddrinfo ENOTFOUND vite.templatus-inertia.test
vite    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
vite    | Exited
browser | Interrupting...
browser | Exited
```

I am on an Mac M1 max if that helps. Every other step of the readme went just fine up until I got to bin/dev.

**Comment by ledermann** [comment]
Glad you found this little project :-)

It seems that `vite.templatus-interia.test` is not accessible on your machine. Are you sure that [puma-dev](https://github.com/puma/puma-dev) is installed and that you have followed [step 3 of the README](https://github.com/templatus/templatus-inertia#getting-started) ?

```markdown
3. Set up `puma-dev` to use HTTPS for development. Do this on macOS:

sudo puma-dev -setup
puma-dev -install
puma-dev link

# Use Vite via puma-dev proxy
# Adopted from https://github.com/puma/puma-dev#webpack-dev-server
echo 3036 > ~/.puma-dev/vite.templatus-inertia
```

The last command adds the subdomain `vite.` to the local domain `templatus-inertia.test`. 

See more about this here:
https://vite-ruby.netlify.app/guide/troubleshooting.html#making-hmr-work-with-puma-dev-in-https-apps

**Comment by TaylorJonesTRT** [comment]
Hey @ledermann !

I am sure puma is installed, I did step 3 a few times actually lol. I'll put the console outputs below for each step

setup:
`╭─    ~/Development/projects/templatus-inertia on    main                                   took   31s at   10:30:08 PM
╰─❯`

install:
`2023/12/11 22:17:52 Existing valid puma-dev CA keypair found. Assuming previously trusted.
 Use '/opt/homebrew/bin/puma-dev' as the location of puma-dev
 Installed puma-dev on ports: http 80, https 443`

And then here is the contents of my puma-dev folder after doing the link command and then the echo command
`* Changing '/etc/resolver/test' to be owned by taylorjones
╭─    ~/Development/projects/templatus-inertia on    main                                    took   3s at   11:30:43 AM
╰─❯
ls ~/.puma-dev
total 16
drwxr-xr-x   6 taylorjones  staff   192 Dec 11 22:18 .
drwxr-x---+ 88 taylorjones  staff  2816 Dec 12 11:32 ..`

I attempted it as well with changing all instances of templatus-inertia to gainlog but ran into the same issue as well.

**Comment by ledermann** [comment]
I don't know what's going wrong on your machine. I have tested the setup on two Macs (M1) without any issues. 

My `~/.puma-dev` folder looks like this:

```
~/.puma-dev ❯ ls -l | grep "templatus-inertia"
lrwxr-xr-x  1 ledermann  staff  43 31 Mai  2022 templatus-inertia -> /Users/ledermann/Projects/templatus-inertia
-rw-r--r--  1 ledermann  staff   5 16 Sep  2022 vite.templatus-inertia
~/.puma-dev ❯ cat ~/.puma-dev/vite.templatus-inertia
3036
```
