### ISSUE TITLE
Internal Error: templatus-inertia@workspace:.: This package doesn't seem to be present in your lockfile

### ISSUE THREAD

**Issue by brobles82** [templatus/templatus-inertia#495]
Trying to setup the project I get this error

Internal Error: templatus-inertia@workspace:.: This package doesn't seem to be present in your lockfile

**Comment by ledermann** [comment]
It seems this was caused by **@sveltejs/vite-plugin-svelte** (https://github.com/sveltejs/vite-plugin-svelte/issues/506) which I have reverted to a former release. Can you confirm the issue is gone?
